name: yourname
on: [push]

jobs:
 your-job-name:
  runs-on: ubuntu-latest
  steps:
  - name: oneliner
    run: echo "hello world"
  - name: multiliner
    run: |
     node -v
     npm -v  
 parallel-job:
  runs-on: macos-latest
  steps:
  - name: Software vwersion
    run: sw_vers
 dependent-job:
  runs-on: windows-latest
  needs: your-job-name
  steps:
  - name: echo a string
    run: Write-Output "Windows"
  - name: Error Step
    run: Doesnot exist
